sudo: required
services:
- docker

language: node_js
node_js:
  - "6"

install: npm install
script:
  - npm run lint
  - npm test

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then bin/docker-build-and-deploy.sh; fi
