version: '2'
services:
  mailer:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - '.:/app'
    ports:
      - "3001:3001"
    depends_on:
      - kinesis
      - ses
      - event-forwarder
    environment:
      NODE_ENV: development
      KINESIS_ENDPOINT: http://kinesis:4567
      SES_ENDPOINT: http://ses:9001
      LISTENER_AUTH_TOKEN: secret
      STREAM_NAME: rabblerouser_stream
    command: npm start
  event-forwarder:
    image: rabblerouser/event-forwarder
    environment:
      KINESIS_ENDPOINT: http://kinesis:4567
      LISTENER_ENDPOINT: http://mailer:3001/events
      LISTENER_AUTH_TOKEN: secret
      STREAM_NAME: rabblerouser_stream
  kinesis:
    image: instructure/kinesalite
  ses:
    image: camjackson/aws-ses-local
    volumes:
      - ./sent-mail:/aws-ses-local/output
